---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket and DynamoDB for terraform state

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
      - AttributeName: "LockID"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "LockID"
        KeyType: HASH

Outputs:

  S3Bucket:
    Value: !Ref S3Bucket
    Description: S3 Bucket for object storage

  TableName:
    Value: !Ref 'DynamoDBTable'
    Description: Table name of the newly created DynamoDB table